//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvertisementList.EditAdvertisementWebPart {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class EditAdvertisementWebPart {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "14.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(EditAdvertisementWebPart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControlTree(global::AdvertisementList.EditAdvertisementWebPart.EditAdvertisementWebPart @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<!DOCTYPE html>\r\n<!--[if lt IE 7 ]><html class=\"ie ie6\" lang=\"en\"> <![endif]-" +
                        "->\r\n<!--[if IE 7 ]><html class=\"ie ie7\" lang=\"en\"> <![endif]-->\r\n<!--[if IE 8 ]>" +
                        "<html class=\"ie ie8\" lang=\"en\"> <![endif]-->\r\n<!--[if (gte IE 9)|!(IE)]><!--><ht" +
                        "ml lang=\"ru\"> <!--<![endif]-->\r\n\r\n<head>\r\n\t<meta charset=\"utf-8\">\r\n\t<title>Загол" +
                        "овок</title>\r\n\t<meta name=\"description\" content=\"\">\r\n\r\n\t<meta http-equiv=\"X-UA-C" +
                        "ompatible\" content=\"IE=edge\">\r\n\t<meta name=\"viewport\" content=\"width=device-widt" +
                        "h, initial-scale=1, maximum-scale=1\">\r\n\t\r\n\t<link rel=\"stylesheet\" href=\"../_layo" +
                        "uts/15/AdvertisementList/css/owl.carousel.min.css\">\r\n\t<link rel=\"stylesheet\" hre" +
                        "f=\"../_layouts/15/AdvertisementList/css/owl.theme.default.min.css\">\r\n    <link r" +
                        "el=\"icon\" href=\"../_layouts/15/AdvertisementList/img/online-shopping.png\">\r\n\r\n\t<" +
                        "link rel=\"stylesheet\" href=\"../_layouts/15/AdvertisementList/libs/bootstrap/css/" +
                        "bootstrap-grid.min.css\">\r\n\t<link href=\"https://fonts.googleapis.com/css?family=R" +
                        "oboto:300,400,500,700,900&amp;subset=cyrillic,cyrillic-ext\" rel=\"stylesheet\">\r\n\t" +
                        "<link rel=\"stylesheet\" href=\"../_layouts/15/AdvertisementList/css/main.css\">\r\n\t<" +
                        "link rel=\"stylesheet\" href=\"../_layouts/15/AdvertisementList/css/media.css\">\r\n  " +
                        "  <link rel=\"stylesheet\" href=\"https://unpkg.com/dropzone@5/dist/min/dropzone.mi" +
                        "n.css\" type=\"text/css\" />\r\n\r\n</head>\r\n\r\n<body>\r\n<div id=\"wrapper\">\r\n\t<div class=" +
                        "\"main bg-white\">\r\n\t\t<div class=\"toping-box\">\r\n\t\t\t<div class=\"container\">\r\n\t\t\t\t<u" +
                        "l class=\"pagin\" id=\"sitePath\">\r\n\t\t\t\t\t<li><a href=\"#\">Главная</a></li>\r\n         " +
                        "           <li><a href=\"#\">Объявления</a></li>\r\n\t\t\t\t</ul>\r\n\t\t\t\t<div class=\"title" +
                        "\">Загрузка</div>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t\t<div class=\"container inactive\" id=\"mai" +
                        "n\">\r\n\t\t\t<div class=\"two-columns\">\r\n\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t<div class=\"col-m" +
                        "d-9 col-sm-12\">\r\n\t\t\t\t\t\t<div class=\"content-box\">\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"se" +
                        "ction-padding\">\r\n\t\t\t\t\t\t\t\t<div action=\"\" class=\"default-form edit-form\">\r\n\t\t\t\t\t\t\t" +
                        "\t\t<div class=\"row-inp\">\r\n\t\t\t\t\t\t\t\t\t\t<p class=\"label\">Заголовок</p>\r\n\t\t\t\t\t\t\t\t\t\t<in" +
                        "put type=\"text\" class=\"edit-title\">\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div class=\"row-i" +
                        "np\">\r\n\t\t\t\t\t\t\t\t\t\t<p class=\"label\">Категории</p>\r\n\t\t\t\t\t\t\t\t\t\t<select class=\"form-co" +
                        "ntrol\" id=\"Categories\">\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"\" disabled>Загрузка</option>\r" +
                        "\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div class=\"row-inp\">\r\n\t\t\t\t\t\t\t\t\t" +
                        "\t<p class=\"label\">Описание</p>\r\n\t\t\t\t\t\t\t\t\t\t<textarea class=\"edit-description\"></t" +
                        "extarea>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div class=\"row-inp\">\r\n                     " +
                        "                   <p class=\"label\">Фотографии, не более 3</p>\r\n\t\t\t\t\t\t\t\t\t\t<!--<d" +
                        "iv class=\"file\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input id=\"file4\" type=\"file\" title=\"Загрузите фото" +
                        "\" multiple/>\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"file-input-text\">name.png</span> -->\r\n    " +
                        "                                    <div class=\"dropzone\" id=\"dz\"></div>\r\n\t\t\t\t\t\t" +
                        "\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<!--</div>\r\n\t\t\t\t\t\t\t\t\t\t<ul class=\"download-images\">\r\n\t\t\t\t\t\t\t" +
                        "\t\t\t</ul>\r\n\t\t\t\t\t\t\t\t\t</div>-->\r\n\t\t\t\t\t\t\t\t\t<div class=\"row-inp\">\r\n\t\t\t\t\t\t\t\t\t\t<p class" +
                        "=\"label\">Объявление будет отправлено на модерацию</p>\r\n\t\t\t\t\t\t\t\t\t\t<input class=\"b" +
                        "tn publish\" type=\"button\" value=\"Сохранить\">\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t</div>\r\n\t" +
                        "\t\t\t\t\t\t</div>\r\n\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div class=\"col-md-3 col-sm-12\">" +
                        "\r\n\t\t\t\t\t\t<div class=\"aside aside-moved-top inactive\" id=\"admin-panel\">\r\n\t\t\t\t\t\t\t<d" +
                        "iv class=\"aside-box news-archive\">\r\n\t\t\t\t\t\t\t\t<div class=\"aside-title title\" id=\"s" +
                        "tatus\">Загрузка</div>\r\n\t\t\t\t\t\t\t\t<a href=\"#change\" class=\"btn publish\" type=\"butto" +
                        "n\" id=\"changeStatus\">Опубликовать</a>\r\n\t\t\t\t\t\t\t\t<ul class=\"month-list\">\r\n\t\t\t\t\t\t\t\t" +
                        "\t<li><a href=\"\">В архив</a></li>\r\n\t\t\t\t\t\t\t\t\t<li><a href=\"#delete\">Удалить</a></li" +
                        "  \r\n\t\t\t\t\t\t\t\t</ul>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t</di" +
                        "v>\r\n\t\t</div>\r\n\t</div>\r\n\t<div class=\"footer footer-inner\">\r\n\t\t<div class=\"contain" +
                        "er\">\r\n\t\t\t<div class=\"row\">\r\n\t\t\t\t<div class=\"col-sm-12\">\r\n\t\t\t\t\t<div class=\"wrap\">" +
                        "\r\n\t\t\t\t\t\t<div class=\"copy\">© 2018 РН Банк. Корпоративный портал сотрудников банка" +
                        ".</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n</div>\r\n\r\n\r\n\t<!-" +
                        "-[if lt IE 9]>\r\n\t<script src=\"libs/html5shiv/es5-shim.min.js\"></script>\r\n\t<scrip" +
                        "t src=\"libs/html5shiv/html5shiv.min.js\"></script>\r\n\t<script src=\"libs/html5shiv/" +
                        "html5shiv-printshiv.min.js\"></script>\r\n\t<script src=\"libs/respond/respond.min.js" +
                        "\"></script>\r\n\t<![endif]-->\r\n\r\n\t<script src=\"../_layouts/15/AdvertisementList/lib" +
                        "s/jquery/jquery-1.11.2.min.js\"></script>\r\n    <script src=\"../_layouts/15/Advert" +
                        "isementList/js/owl.carousel.js\"></script>\r\n    <script src=\"../_layouts/15/Adver" +
                        "tisementList/js/jcf.js\"></script>\r\n\t<script src=\"../_layouts/15/AdvertisementLis" +
                        "t/js/jcf.checkbox.js\"></script>\r\n\t<script src=\"../_layouts/15/AdvertisementList/" +
                        "js/jcf.radio.js\"></script>\r\n\t<script src=\"../_layouts/15/AdvertisementList/libs/" +
                        "plugins-scroll/plugins-scroll.js\"></script>\r\n\t<script src=\"../_layouts/15/Advert" +
                        "isementList/js/common.js\"></script>\r\n    <script src=\"../_layouts/15/Advertiseme" +
                        "ntList/utils/helper.js\"></script>\r\n    <script src=\"../_layouts/15/Advertisement" +
                        "List/js/editAdvertisement.js\"></script>\r\n    <script src=\"https://unpkg.com/drop" +
                        "zone@5/dist/min/dropzone.min.js\"></script>\r\n    <script type=\"text/javascript\"> " +
                        "Dropzone.autoDiscover = false; /* Prevent Dropzone from doing auto stuff */ </sc" +
                        "ript>\r\n\t\r\n</body>\r\n</html>"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
